[package]
name = "pcap2mpegts"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.5.1"
etherparse = "0.14.2"
pcap-parser = { version = "0.15.0", features = ["data"] }
